-- Add new products to the catalog
INSERT INTO products (slug, title, description, price_cents, currency, tags, region_code, images, in_stock) VALUES
('1001-noch', '1001 ночь, кг', 'Пряный сыр с восточными специями и характерным вкусом.', 180500, 'RUB', ARRAY['cheese', 'spiced', 'russian'], 'RU', ARRAY['/images/1001.png'], true),
('1001-noch-lysoy', '1001 ночь лысый, кг', 'Пряный сыр без корочки с восточными специями.', 161000, 'RUB', ARRAY['cheese', 'spiced', 'russian'], 'RU', ARRAY['/images/1001.png'], true),
('bavaria-blue', 'Бавария Блю, кг', 'Немецкий голубой сыр из Баварии с нежным вкусом.', 196500, 'RUB', ARRAY['cheese', 'blue', 'german'], 'DE', ARRAY['/images/Дорблю.png'], true),
('basiron-blue', 'Базирон Блю, кг', 'Голландский голубой сыр с бархатистым вкусом.', 219000, 'RUB', ARRAY['cheese', 'blue', 'dutch'], 'NL', ARRAY['/images/Дорблю.png'], true),
('basiron-dikiy-chesnok', 'Базирон Дикий Чеснок, кг', 'Сыр с ароматом дикого чеснока.', 165000, 'RUB', ARRAY['cheese', 'flavored', 'dutch'], 'NL', ARRAY['/images/1001.png'], true),
('basiron-zatara', 'Базирон Затара, кг', 'Сыр с травами Затара.', 165000, 'RUB', ARRAY['cheese', 'herbs', 'dutch'], 'NL', ARRAY['/images/1001.png'], true),
('basiron-krasnoe-pesto', 'Базирон Красное Песто, кг', 'Сыр с красным песто.', 186000, 'RUB', ARRAY['cheese', 'pesto', 'dutch'], 'NL', ARRAY['/images/1001.png'], true),
('basiron-perets-luk', 'Базирон Перец / Лук, кг', 'Сыр с перцем и луком.', 165000, 'RUB', ARRAY['cheese', 'flavored', 'dutch'], 'NL', ARRAY['/images/1001.png'], true),
('basiron-pivo', 'Базирон Пиво, кг', 'Сыр с ароматом пива.', 165000, 'RUB', ARRAY['cheese', 'flavored', 'dutch'], 'NL', ARRAY['/images/1001.png'], true),
('basiron-trikolor', 'Базирон Триколор, кг', 'Сыр триколор с разноцветными слоями.', 256500, 'RUB', ARRAY['cheese', 'flavored', 'dutch'], 'NL', ARRAY['/images/1001.png'], true),
('basiron-tryufel', 'Базирон Трюфель, кг', 'Премиальный сыр с трюфелем.', 219000, 'RUB', ARRAY['cheese', 'truffle', 'dutch', 'premium'], 'NL', ARRAY['/images/1001.png'], true),
('basiron-chernyy-limon', 'Базирон Черный лимон, кг', 'Сыр с черным лимоном.', 256500, 'RUB', ARRAY['cheese', 'flavored', 'dutch'], 'NL', ARRAY['/images/1001.png'], true),
('batistella-brilliant', 'Батистелла Бриллиант, кг', 'Итальянский сыр Батистелла.', 305500, 'RUB', ARRAY['cheese', 'italian'], 'IT', ARRAY['/images/1001.png'], true),
('batistella-seno', 'Батистелла сено, кг', 'Батистелла с ароматом сена.', 235500, 'RUB', ARRAY['cheese', 'italian'], 'IT', ARRAY['/images/1001.png'], true),
('batistella-shampanskoe', 'Батистелла Шампанское, кг', 'Батистелла с шампанским.', 201500, 'RUB', ARRAY['cheese', 'italian'], 'IT', ARRAY['/images/1001.png'], true),
('bebibel-120g', 'Бебибел 120г, шт', 'Мини-сыр Бебибел в индивидуальной упаковке.', 52500, 'RUB', ARRAY['cheese', 'mini', 'french'], 'FR', ARRAY['/images/brie.png'], true),
('bebibel-fiolet-120g', 'Бебибел Фиолет. 120г, шт', 'Мини-сыр Бебибел фиолетовый.', 52500, 'RUB', ARRAY['cheese', 'mini', 'french'], 'FR', ARRAY['/images/brie.png'], true),
('belgrano-koziy', 'Белграно Козий, кг', 'Аргентинский козий сыр.', 186000, 'RUB', ARRAY['cheese', 'goat', 'argentine'], 'AR', ARRAY['/images/1001.png'], true),
('bri-125gr', 'Бри 125гр, шт', 'Французский сыр Бри в порционной упаковке.', 28500, 'RUB', ARRAY['cheese', 'soft', 'bloomy', 'french'], 'FR', ARRAY['/images/brie.png'], true),
('bri-petit-france-1kg', 'Бри Петит Франция 1кг, кг', 'Французский Бри малый весом 1 кг.', 180500, 'RUB', ARRAY['cheese', 'soft', 'bloomy', 'french'], 'FR', ARRAY['/images/brie-de-meaux-1.jpg'], true),
('velkhuzien-med', 'Велхюзен Мед, кг', 'Голландский сыр Велхюзен с медом.', 213500, 'RUB', ARRAY['cheese', 'flavored', 'dutch'], 'NL', ARRAY['/images/1001.png'], true),
('velkhuzien-siniy', 'Велхюзен Синий, кг', 'Голландский голубой сыр Велхюзен.', 213500, 'RUB', ARRAY['cheese', 'blue', 'dutch'], 'NL', ARRAY['/images/Дорблю.png'], true),
('velkhuzien-ho', 'Велхюзен ХО, кг', 'Велхюзен выдержанный ХО.', 219000, 'RUB', ARRAY['cheese', 'aged', 'dutch'], 'NL', ARRAY['/images/1001.png'], true),
('velkhuzien-cherniy-old', 'Велхюзен Черний Олд, кг', 'Велхюзен черный выдержанный.', 208000, 'RUB', ARRAY['cheese', 'aged', 'dutch'], 'NL', ARRAY['/images/1001.png'], true),
('vino-abriagoni', 'Вино абриагони, кг', 'Сыр с вином Абриагони.', 208000, 'RUB', ARRAY['cheese', 'flavored', 'italian'], 'IT', ARRAY['/images/1001.png'], true),
('gorgonzola-leonardi', 'Гарганзола Леонарди, кг', 'Итальянский голубой сыр Горгонзола.', 219000, 'RUB', ARRAY['cheese', 'blue', 'italian'], 'IT', ARRAY['/images/Gorgonzola.jpg'], true),
('goshe', 'Гоше, кг', 'Французский козий сыр Гоше.', 219000, 'RUB', ARRAY['cheese', 'goat', 'french'], 'FR', ARRAY['/images/1001.png'], true),
('gran-albiero-kus', 'Гран Альбиеро Кус., кг', 'Испанский сыр Гран Альбиеро кусковой.', 180500, 'RUB', ARRAY['cheese', 'spanish'], 'ES', ARRAY['/images/1001.png'], true),
('gran-muraviya', 'Гран Муравия, кг', 'Испанский сыр Гран Муравия.', 174500, 'RUB', ARRAY['cheese', 'spanish'], 'ES', ARRAY['/images/1001.png'], true),
('grana-padana-cantarele', 'Грана Падана (Кантарель), кг', 'Итальянский сыр Грана Падана.', 262500, 'RUB', ARRAY['cheese', 'hard', 'italian'], 'IT', ARRAY['/images/grana.png'], true),
('grana-padano-kuskovoy', 'Грана падано кусковой, кг', 'Итальянский сыр Грана Падано кусковой.', 208000, 'RUB', ARRAY['cheese', 'hard', 'italian'], 'IT', ARRAY['/images/grana.png'], true),
('grana-podana-gol', 'Грана Подана Гол, кг', 'Грана Падана голый.', 201500, 'RUB', ARRAY['cheese', 'hard', 'italian'], 'IT', ARRAY['/images/grana.png'], true),
('grandano-pradera', 'Грандано (Прадера), кг', 'Испанский сыр Грандано.', 213500, 'RUB', ARRAY['cheese', 'spanish'], 'ES', ARRAY['/images/1001.png'], true),
('grandano-pradera-matur', 'Грандано (Прадера) Матур, кг', 'Грандано выдержанный.', 208000, 'RUB', ARRAY['cheese', 'aged', 'spanish'], 'ES', ARRAY['/images/1001.png'], true),
('grudka-indeyki-gril-elpazo', 'Грудка Индейки Гриль Элпозо, кг', 'Грудка индейки гриль.', 191000, 'RUB', ARRAY['meat', 'chicken', 'grilled'], 'ES', ARRAY['/images/1001.png'], true),
('gruver', 'Грювер, кг', 'Голландский сыр Грювер.', 186000, 'RUB', ARRAY['cheese', 'dutch'], 'NL', ARRAY['/images/gryuyer_aop.jpg'], true),
('guanchela-podushka', 'Гуанчела Подушка, кг', 'Испанский сыр Гуанчела.', 208000, 'RUB', ARRAY['cheese', 'spanish'], 'ES', ARRAY['/images/1001.png'], true),
('gudbrand-krasniy-1kg', 'Гудбранд Красний 1кг, кг', 'Норвежский сыр Гудбранд красный.', 213500, 'RUB', ARRAY['cheese', 'norwegian'], 'NO', ARRAY['/images/1001.png'], true),
('dzhersi-chernyy', 'Джерси черный, кг', 'Английский сыр Джерси черный.', 208000, 'RUB', ARRAY['cheese', 'english'], 'GB', ARRAY['/images/1001.png'], true),
('dorblu-zelenyy', 'Дорблю зеленый, кг', 'Немецкий голубой сыр Дорблю зеленый.', 131000, 'RUB', ARRAY['cheese', 'blue', 'german'], 'DE', ARRAY['/images/Дорблю.png'], true),
('dorblu-zelenyy-original', 'Дорблю зеленый оригинал, кг', 'Оригинальный Дорблю зеленый.', 147000, 'RUB', ARRAY['cheese', 'blue', 'german'], 'DE', ARRAY['/images/Дорблю.png'], true),
('dorblu-chernyy-original', 'Дорблю черный оригинал, кг', 'Оригинальный Дорблю черный.', 219000, 'RUB', ARRAY['cheese', 'blue', 'german'], 'DE', ARRAY['/images/Дорблю.png'], true),
('il-pikkolo', 'Иль Пиколло, кг', 'Итальянский сыр Иль Пиколло.', 278500, 'RUB', ARRAY['cheese', 'italian'], 'IT', ARRAY['/images/1001.png'], true),
('ilchestr-klyukva', 'Ильчестр Клюква, кг', 'Английский сыр Ильчестр с клюквой.', 219000, 'RUB', ARRAY['cheese', 'flavored', 'english'], 'GB', ARRAY['/images/1001.png'], true),
('ilchestr-meksikano', 'Ильчестр Мексикано, кг', 'Ильчестр с мексиканскими специями.', 186000, 'RUB', ARRAY['cheese', 'spiced', 'english'], 'GB', ARRAY['/images/1001.png'], true),
('ilchestr-shokolad-apelsin', 'Ильчестр Шоколад апельсин, кг', 'Ильчестр с шоколадом и апельсином.', 219000, 'RUB', ARRAY['cheese', 'flavored', 'english'], 'GB', ARRAY['/images/1001.png'], true),
('irlandskiy-chedder-shalfey-150g', 'Ирландский чеддер шалфей 150г, шт', 'Ирландский чеддер с шалфеем.', 30500, 'RUB', ARRAY['cheese', 'cheddar', 'flavored', 'irish'], 'IE', ARRAY['/images/1001.png'], true),
('kambazola-klassik', 'Камбазола Классик, кг', 'Итальянский голубой сыр Камбазола.', 240500, 'RUB', ARRAY['cheese', 'blue', 'italian'], 'IT', ARRAY['/images/Gorgonzola.jpg'], true),
('castello-ananas-125gr', 'Кастелло Ананас 125гр, шт', 'Датский сыр с ананасом.', 40000, 'RUB', ARRAY['cheese', 'flavored', 'danish'], 'DK', ARRAY['/images/1001.png'], true),
('castello-ananas-1kg', 'Кастелло Ананас 1кг, кг', 'Датский сыр с ананасом 1 кг.', 219000, 'RUB', ARRAY['cheese', 'flavored', 'danish'], 'DK', ARRAY['/images/1001.png'], true),
('kinara-tryufel-200g', 'Кинара Трюфель 200г., шт', 'Итальянский сыр Кинара с трюфелем.', 74500, 'RUB', ARRAY['cheese', 'truffle', 'italian', 'premium'], 'IT', ARRAY['/images/1001.png'], true),
('kinara-tryufel-gol', 'Кинара Трюфель Гол., кг', 'Кинара трюфель голый.', 267500, 'RUB', ARRAY['cheese', 'truffle', 'italian', 'premium'], 'IT', ARRAY['/images/1001.png'], true),
('koziy-friko', 'Козий Фрико, кг', 'Испанский козий сыр Фрико.', 201500, 'RUB', ARRAY['cheese', 'goat', 'spanish'], 'ES', ARRAY['/images/1001.png'], true);
